# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build image
      run: docker build . -t shanmugacv/squid_elite_proxy:latest

    - name: push image
      run: |
        docker login --username $DOCKER_USER --password $DOCKER_TOKEN
        docker push shanmugacv/squid_elite_proxy:latest
        docker logout
      env:
        DOCKER_USER: ${{ secrets.docker_user }}
        DOCKER_TOKEN: ${{ secrets.docker_token }}
